//! Every tag ExifTool reports (for the names the backend asks for) must be
//! reported by us with the same group and value. Skips without exiftool.
use photo_meta::{Value, read};
use serde_json::Value as J;
use std::path::{Path, PathBuf};
use std::process::Command;

const NAMES: &[&str] = &[
    "Software", "CreatorTool", "DigitalSourceType", "Description", "Comment", "Encoder", "UserComment",
    "Parameters", "GenerationParameters", "Prompt", "Workflow", "ColorSpace", "ColorType",
    "PhotometricInterpretation", "SamplesPerPixel", "BitsPerSample", "BitDepth", "ColorComponents",
    "ProfileDescription", "ProfileID", "Orientation",
];

fn run(cmd: &mut Command) -> bool {
    cmd.stdout(std::process::Stdio::null()).stderr(std::process::Stdio::null()).status().map(|s| s.success()).unwrap_or(false)
}

fn fixtures(dir: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    let ff = |args: &[&str], name: &str| -> Option<PathBuf> {
        let p = dir.join(name);
        run(Command::new("ffmpeg").args(["-y", "-v", "error"]).args(args).arg(&p)).then_some(p)
    };
    let tone = ["-f", "lavfi", "-i", "sine=f=440:d=0.2", "-metadata", "encoder=Suno v4", "-metadata", "comment=generated by Suno", "-metadata", "description=AI song"];
    for (name, extra) in [
        ("a.wav", &["-c:a", "pcm_s16le"][..]),
        ("a.flac", &["-c:a", "flac"][..]),
        ("a.m4a", &["-c:a", "alac"][..]),
        ("a.aiff", &["-write_id3v2", "1", "-c:a", "pcm_s16be"][..]),
        ("a.wv", &["-c:a", "wavpack"][..]),
        ("a.tta", &["-c:a", "tta"][..]),
    ] {
        let mut args: Vec<&str> = tone.to_vec();
        args.extend_from_slice(extra);
        if let Some(p) = ff(&args, name) {
            out.push(p);
        }
    }
    let py = r#"
import sys
from PIL import Image, PngImagePlugin, ImageCms
d=sys.argv[1]
im=Image.new("RGB",(16,16),"red")
i=PngImagePlugin.PngInfo()
i.add_text("parameters","A cat\nSteps: 20, Sampler: Euler, CFG scale: 7, Seed: 1")
i.add_text("Software","ComfyUI")
i.add_itxt("Comment","AI generated",lang="en",zip=True)
im.save(f"{d}/p.png",pnginfo=i,icc_profile=ImageCms.ImageCmsProfile(ImageCms.createProfile("sRGB")).tobytes())
im.convert("RGBA").save(f"{d}/rgba.png")
im.save(f"{d}/j.jpg",quality=80)
im.convert("CMYK").save(f"{d}/cmyk.jpg")
im.convert("L").save(f"{d}/g.png")
"#;
    if run(Command::new("python3").args(["-c", py]).arg(dir)) {
        for n in ["p.png", "rgba.png", "cmyk.jpg", "g.png"] {
            out.push(dir.join(n));
        }
        let j = dir.join("j.jpg");
        let ok = run(Command::new("exiftool").args([
            "-q", "-overwrite_original",
            "-EXIF:Software=Adobe Firefly", "-EXIF:Orientation#=6", "-EXIF:ColorSpace#=1",
            "-EXIF:UserComment=Made with Midjourney", "-EXIF:ImageDescription=cover",
            "-XMP-xmp:CreatorTool=Stable Diffusion",
            "-XMP-iptcExt:DigitalSourceType=http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia",
            "-XMP-dc:Description=AI art", "-Comment=jpeg comment",
        ]).arg(&j));
        if ok {
            out.push(j);
        }
    }
    out
}

fn ours(path: &Path) -> Vec<(String, String)> {
    let m = read(&std::fs::read(path).unwrap()).unwrap();
    m.tags
        .iter()
        .filter(|t| NAMES.contains(&t.name.as_str()))
        .map(|t| {
            let v = match &t.value {
                Value::Int(i) => i.to_string(),
                Value::Real(r) => r.to_string(),
                Value::Text(s) => s.clone(),
                Value::List(l) => l.join(", "),
            };
            (format!("{}:{}", t.group, t.name), v)
        })
        .collect()
}

fn exiftool(path: &Path) -> Option<Vec<(String, String)>> {
    let mut cmd = Command::new("exiftool");
    cmd.args(["-j", "-n", "-G1", "-s", "-a"]);
    for n in NAMES {
        cmd.arg(format!("-{n}"));
    }
    let out = cmd.arg(path).output().ok()?;
    let v: J = serde_json::from_slice(&out.stdout).ok()?;
    let obj = v.as_array()?.first()?.as_object()?.clone();
    Some(
        obj.into_iter()
            .filter(|(k, _)| k != "SourceFile")
            .map(|(k, v)| {
                let s = match v {
                    J::String(s) => s,
                    J::Array(a) => a.iter().map(|x| x.as_str().map_or(x.to_string(), str::to_owned)).collect::<Vec<_>>().join(", "),
                    other => other.to_string(),
                };
                (k, s)
            })
            .collect(),
    )
}

#[test]
fn superset_of_exiftool() {
    if !run(Command::new("exiftool").arg("-ver")) {
        eprintln!("exiftool unavailable; skipping");
        return;
    }
    let dir = std::env::temp_dir().join(format!("photo-meta-{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    let files = fixtures(&dir);
    assert!(files.len() >= 8, "fixtures: {files:?}");
    let mut missing = Vec::new();
    for f in &files {
        let theirs = exiftool(f).unwrap();
        let mine = ours(f);
        for (k, v) in &theirs {
            let ok = mine.iter().any(|(mk, mv)| mk == k && (mv == v || mv.parse::<f64>().ok() == v.parse::<f64>().ok() && mv.parse::<f64>().is_ok()));
            if !ok {
                missing.push(format!("{}: {k} = {v:?} (ours: {:?})", f.file_name().unwrap().to_string_lossy(), mine.iter().filter(|(mk, _)| mk.ends_with(k.rsplit(':').next().unwrap())).collect::<Vec<_>>()));
            }
        }
        let extra: Vec<_> = mine.iter().filter(|(k, _)| !theirs.iter().any(|(tk, _)| tk == k)).collect();
        eprintln!("{}: exiftool {} tags, ours {} (extra {:?})", f.file_name().unwrap().to_string_lossy(), theirs.len(), mine.len(), extra);
    }
    std::fs::remove_dir_all(&dir).ok();
    assert!(missing.is_empty(), "missing:\n{}", missing.join("\n"));
}
