[package]
name = "photo-pdf-jpeg2000"
description = "JPEG 2000 decoder (from hayro-jpeg2000)"
version.workspace = true
edition.workspace = true
rust-version = "1.92"
license = "Apache-2.0 OR MIT"

[features]
default = ["std", "simd"]
std = []
simd = ["dep:fearless_simd", "std"]
logging = ["dep:log"]

[dependencies]
log = { workspace = true, optional = true }
fearless_simd = { workspace = true, optional = true }

[lints]
workspace = true
