[package]
name = "photo-png"
description = "PNG decoder, encoder and strict signature validator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
photo-core.workspace = true
photo-deflate.workspace = true

[lints]
workspace = true
